FROM python:3.11-alpine

ENV PYTHONBUFFERED=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /posts
COPY . /posts

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

